name: C/C++ CI

on:
  push:
    branches: [ master, experimental ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1
    - uses: actions/checkout@v2
    - name: Install platform
      run: arduino-cli core update-index
    - name: Show List of installed libraries on clear system
      run: arduino-cli lib list
    - name: Install dependencies
      run: |
          arduino-cli lib install AceButton 
          arduino-cli lib install Array 
          arduino-cli lib install EveryTimer 
          arduino-cli lib install MIDIUSB 
          arduino-cli lib install TimerOne 
          arduino-cli lib install "LiquidCrystal I2C"
    - name: Show List of installed libraries after installing dependencies
      run: arduino-cli lib list
    - name: Compile C++20
      run: arduino-cli compile --fqbn arduino:avr:leonardo --verify --warnings all --build-properties std=c++1z
